import os
import json
import psycopg2
import datetime
from openai import OpenAI
from dotenv import load_dotenv

# --- CONFIGURATION ---
load_dotenv()

# Using the same live database URL from app.py
DATABASE_URL = os.getenv("DATABASE_URL", "postgresql://neondb_owner:npg_ZWb5lX1Hhgre@ep-empty-shape-aln50nml-pooler.c-3.eu-central-1.aws.neon.tech/neondb?sslmode=require")

# Configure this to match your local LLM server (Ollama, LM Studio, etc.)
LOCAL_LLM_URL = os.getenv("LOCAL_LLM_URL", "http://localhost:11434/v1")
LOCAL_MODEL_NAME = os.getenv("LOCAL_MODEL_NAME", "llama3.2")

client = OpenAI(base_url=LOCAL_LLM_URL, api_key="local-no-key-required")

VOXA_BRAND_IDENTITY = """
BRAND NAME: Voxa
SLOGAN: "Apply now, get hired yesterday."
MISSION: To revolutionize recruitment in Egypt by allowing candidates to apply for jobs using simply a Voice Note on our dedicated platform—no traditional CV required.
MARKET POSITIONING: There are many recruitment agencies in Egypt, but none have a dedicated, seamless website or operate as efficiently and fast as Voxa. Emphasize our speed and tech-forward approach.
VISUAL IDENTITY & COLORS: Primary colors are Light Blue (#34A8FF), Purple/Magenta (#954CE5), Dark Navy Background (#091122), and Pure White Text (#FFFFFF). The aesthetic is modern, clean, cinematic, and tech-forward. The Voxa logo or brand colors must naturally blend into the environment or wardrobe.
ULTIMATE GOAL: Drive massive traffic to the Voxa website. Convert job seekers into registered users by selling them on how incredibly easy it is to apply.
TONE OF VOICE: Innovative, empowering, energetic, Egyptian-youth friendly, and highly professional.
"""

def get_active_jobs():
    """Fetch active jobs from the Voxa database."""
    conn = psycopg2.connect(DATABASE_URL)
    cur = conn.cursor()
    try:
        cur.execute('SELECT "JobID", "JobTitle", "CompanyName", "SalaryPackage", "Location", "WorkingHours" FROM "Jobs" WHERE "Status" = \'Active\'')
        cols = [desc[0] for desc in cur.description]
        jobs = [dict(zip(cols, row)) for row in cur.fetchall()]
        return jobs
    except Exception as e:
        print(f"❌ Database Error: {e}")
        return []
    finally:
        cur.close()
        conn.close()

def get_past_analytics():
    """
    Reads past performance analytics from a local file so the AI can learn from mistakes.
    Create a 'past_analytics.json' or text file in this folder and jot down notes 
    on what worked and what failed each week!
    """
    analytics_path = os.path.join(os.path.dirname(__file__), "past_analytics.json")
    if os.path.exists(analytics_path):
        with open(analytics_path, "r", encoding="utf-8") as f:
            return f.read()
            
    # Fallback simulated analytics if the file doesn't exist yet
    return """
    PAST PERFORMANCE INSIGHTS (EGYPT TARGET AUDIENCE):
    - Posts mentioning "11K Net Salary" in the first line got 40% more clicks.
    - Emojis like 🚀 and 💸 work best on Instagram, but perform poorly on LinkedIn.
    - Facebook posts that ask "Send your Voice Note in the comments" got 3x more engagement.
    - Last week's image prompt that was too "corporate" failed; vibrant, youth-focused imagery works better.
    - TikTok videos under 10 seconds with trending audio hooks retain 80% more viewers.
    """

def generate_weekly_schedule(jobs, analytics_data):
    """Use a local LLM to generate a full weekly markdown schedule based on jobs and analytics."""
    
    # 1. Load the latest guidelines
    guidelines_path = os.path.join(os.path.dirname(__file__), "platform_guidelines.json")
    if os.path.exists(guidelines_path):
        try:
            with open(guidelines_path, "r", encoding="utf-8") as f:
                rules = json.load(f)
        except json.JSONDecodeError as e:
            print(f"⚠️ Warning: platform_guidelines.json contains invalid JSON generated by the AI ({e}). Falling back to default rules.")
            rules = {"linkedin": "Professional", "facebook": "Engaging", "instagram": "Visual, no links in caption", "tiktok": "Short hook"}
    else:
        print("⚠️ Warning: platform_guidelines.json not found. Run update_guidelines.py first! Falling back to default rules.")
        rules = {"linkedin": "Professional", "facebook": "Engaging", "instagram": "Visual, no links in caption", "tiktok": "Short hook"}

    # Take up to 7 jobs for the week
    jobs_sample = jobs[:7]
    jobs_text = json.dumps(jobs_sample, indent=2)

    current_time = datetime.datetime.now().strftime("%A, %B %d, %Y at %I:%M %p (Cairo Time)")

    prompt = f"""
    <role>
    You are Voxa's Elite Marketing Agency, Lead Copywriter, and Expert Social Media Strategist. Your primary goal is to drive massive traffic to the Voxa website via the Egyptian job market.
    </role>
    
    <brand_identity>
    {VOXA_BRAND_IDENTITY}
    AUDIENCE PSYCHOLOGY: Egyptian job seekers are frustrated with traditional CVs, slow responses, and complicated portals. They want speed, respect, and tech.
    LANGUAGE INSTRUCTIONS: You MUST write the social media captions using a highly engaging, natural mix of English and Egyptian Arabic dialect (Franco-Arabic). Ensure it sounds completely human, using slang and avoiding overly formal AI-speak.
    </brand_identity>
    
    <context>
    CURRENT DATE & TIME: {current_time}
    You MUST start your 7-day schedule from today.
    
    AVAILABLE JOBS TO PROMOTE THIS WEEK:
    {jobs_text}
    
    PAST ANALYTICS (CRITICAL - DO NOT REPEAT MISTAKES):
    {analytics_data}
    </context>
    
    <platform_guidelines>
    - LinkedIn Rules: {rules.get('linkedin', '')}
    - Facebook Rules: {rules.get('facebook', '')}
    - Instagram Rules: {rules.get('instagram', '')}
    - TikTok Rules: {rules.get('tiktok', '')}
    </platform_guidelines>
    
    <task>
    Create a comprehensive Weekly Social Media Content Calendar (Monday to Sunday) in beautifully formatted Markdown.
    
    FIRST, start with a "📈 Platform Growth Strategy" section. 
    Based on the guidelines, briefly explain to me exactly how often we should be posting on each platform this week to satisfy their algorithms, and what type of engagement we are targeting.
    
    THEN, for each day of the week, select ONE job from the list above to promote.
    </task>
    
    <rules>
    DO NOT generate a post for every platform every day! You must distribute the posts across the week strictly based on the optimal frequency you defined in the Growth Strategy.
    </rules>
    
    <thinking_process>
    You are equipped with a Deep-Thinking Protocol. Before writing the final schedule, you MUST exhaustively plan your work inside <thinking>...</thinking> tags. 
    Inside the <thinking> block, you must:
    1. Analyze the Egyptian target audience and Franco-Arabic nuances for the selected jobs.
    2. Map out all 7 days. Do not skip any day.
    3. Assign platforms to each day based on the frequency rules (ensuring TikTok is included 3-4 times).
    4. Brainstorm the visual aesthetics and hooks based on the Audience Psychology. Write out massive multi-paragraph ideas for the image and video prompts here first before finalizing them.
    5. Double-check that you are planning all 7 days and explicitly outline the narrative for each post.
    Take your absolute time. Be as verbose and detailed as possible in your internal thoughts.
    </thinking_process>
    
    <output_format>
    WARNING: You MUST include TikTok and its VIDEO PROMPT at least 3-4 times this week!
    
    For EVERY single day (Day 1 through Day 7), you MUST copy and fill out this exact template:
    
    ### [Day of the Week], [Date]
    **Time to Post:** [Exact Cairo Time based on the platform guidelines]
    **Platforms Chosen:** [e.g., LinkedIn, TikTok]
    **IMAGE PROMPT:** [CRITICAL: Write a massive, highly-detailed 3-4 paragraph Midjourney/DALL-E style prompt. Detail the lighting, camera angle, subject, Egyptian cultural context, facial expressions, and exactly how the Voxa brand colors (#34A8FF, #954CE5) are integrated. DO NOT write less than 3 paragraphs. Write "None" ONLY if it's a TikTok-only day.]
    **VIDEO PROMPT:** [CRITICAL: Write a full, detailed shot-by-shot description. Describe the camera motion, pacing, lighting, and exact B-Roll footage needed. Write "None" ONLY if TikTok is not chosen today.]
    **Post Content:**
    [If Facebook/LinkedIn: Write an exhaustive 3 to 5 paragraph story. Mix English and Egyptian Arabic naturally. Tell a compelling story of a frustrated applicant finding success with Voxa's "Voice Note" revolution.]
    [If Instagram: Deep, engaging Egyptian-English mix, bullet points, emojis. Highly relatable content.]
    [If TikTok: Write the FULL 30-to-60 second spoken script. Include exactly what the presenter is doing with their hands, exact text overlay instructions popping on screen, and the specific trending audio vibe to use.]
    **Hashtags:** [List 3-5 tags]
    
    Output your <thinking> block first, followed immediately by the beautifully formatted Markdown text. Do not output JSON.
    </output_format>
    """
    
    print(f"🤖 Local LLaMA 3.2 is deep-thinking to craft the ultimate Weekly Egyptian Social Schedule...")
    try:
        response = client.chat.completions.create(
            model=LOCAL_MODEL_NAME,
            messages=[{"role": "user", "content": prompt}],
            temperature=0.6
        )
        
        # Return raw Markdown text
        return response.choices[0].message.content.strip()
    except Exception as e:
        print(f"\n❌ Error communicating with local LLM API: {e}")
        print("⚠️ Please ensure your local LLM server is running and the model name is correct.")
        return None

if __name__ == "__main__":
    print("🚀 Voxa AI Social Media Bot Initialized!")
    jobs = get_active_jobs()
    analytics = get_past_analytics()
    print(f"📊 Found {len(jobs)} active jobs in the database.")
    
    if jobs:
        schedule = generate_weekly_schedule(jobs, analytics)
        if schedule:
            # Save the content to a Markdown file
            output_path = os.path.join(os.path.dirname(__file__), "weekly_social_media_plan.md")
            with open(output_path, "w", encoding="utf-8") as f:
                f.write(schedule)
            print(f"\n✅ Generation Complete! Your weekly plan has been saved to: {output_path}")
        else:
            print("\n❌ Failed to generate social content due to an API error.")
